# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0644ad7d9fc0b978a68fcd3e3b9540901d5898be37735158e170d039003f2e9e8058a6139413a6d40df7dcf099fdb49b6421ae933c5fb33cfd091b65219a560d

test:
  secret_key_base: 4fafa208929d6af782b67fe46aff68cab0e8281238019ddd710c654ae9702f21783962f07620fd64c089cf980d564e55134a12e8834edfe0bae506565e278e65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
